CREATE TABLE FRIEND_REQUEST_MASTER(
	ID int default 0 unique,
    FROM_USER VARCHAR2(100),
    TO_USER  VARCHAR2(100),
    STATUS INT,
	IS_DELETE INT default 0,
    CONSTRAINT FK_FROM_USER FOREIGN KEY (FROM_USER)
    REFERENCES ACCOUNT_MASTER(EMAIL),
    CONSTRAINT FK_TO_USER FOREIGN KEY (TO_USER)
    REFERENCES ACCOUNT_MASTER(EMAIL)    
);

