CREATE TABLE FRIENDS_MASTER(
	ID int default 0 unique,
    USER_EMAIL VARCHAR2(100),
    FRIEND_EMAIL  VARCHAR2(100),
    CONSTRAINT FK_USER_EMAIL FOREIGN KEY (USER_EMAIL)
    REFERENCES ACCOUNT_MASTER(EMAIL),
    CONSTRAINT FK_FRIEND_EMAIL FOREIGN KEY (FRIEND_EMAIL)
    REFERENCES ACCOUNT_MASTER(EMAIL)    
);

